
data:
    dataset: "histo"
    seed: 12321
    num_classes: 4
    num_workers: 8
    feature_path: lung
    train_set:   brca_files/train_0.txt
    val_set :    brca_files/val_0.txt
    test_set:    brca_files/test_0.txt
model:
    embed_dim: 1024
    feature_dim: 1024
    num_layers: 3
    arch: linear
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: False
    node_cluster_num: 100
    mode: 'kmeans'
tree:
    depth: 3
    n_proto : 16
    proto_size: [1]
    embed_dim : 1024
    proto_dim : 1024
training:
    n_epochs: 50
    snapshot_freq: 1
    batch_size: 4
    logging_freq: 1
    validation_freq: 1
    loss: "nll_loss"
optim:
    weight_decay: 0.00001
    optimizer: "Adam"
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: None
    lr_schedule: True
    min_lr: 0.0
